name: Lint with flake8

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 aiotfm --count --ignore W191,E261,W292,E117 --max-line-length=100 --statistics